name: 'Local Cache on Self-Hosted'
description: 'Cache dependencies and build outputs to improve workflow execution time on self hosted machine'
author: 'Tâm Võ'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

inputs:
  path:
    description: 'An explicit key for versioning the cache'
    required: true
  action:
    description: 'The file or folder to be cached'
    required: false
  cache-key:
    description: 'The path dir will cache'
    required: true
  cache-dir:
    description: 'Action will be run if not cashed yet'
    required: true
  working-directory:
    description: 'working-directory'
    required: false

outputs:
  cache-hit:
    description: 'A boolean value to indicate if cache was found and restored'
    default: 'false'
  action-hit:
    description: 'A boolean value to indicate if action was found and runned'
    default: 'false'

runs:
  using: node20
  main: dist/restore.js
  post: dist/save.js
  post-if: success()
